add_newline = true

format = '''
[╭─](bold red)[ ](bold blue)$directory$git_branch$golang$rust$package$cmd_duration
$character '''

[character] 
#success_symbol = "[╰─󰥳 ](bold red)"
success_symbol = "[╰─ ](bold red)"
#error_symbol = " [╰─󱍢 ](bold green)"
error_symbol = "[╰─󰈸 󰈸 󰈸 ](bold red)"

[aws]
symbol = "  "

[buf]
symbol = " "

[c]
symbol = " "

[conda]
symbol = " "

[crystal]
symbol = " "

[dart]
symbol = " "

[directory]
read_only = " 󰌾"
style = "purple"
truncation_length = 0
truncate_to_repo = true
truncation_symbol = "repo: "

#[directory.substitutions]
#'~/Practice/golang/zerotomastery.io-golang/src/lectures/exercise/' = 'practice_golang'

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[fennel]
symbol = " "

[fossil_branch]
symbol = " "

[git_branch]
symbol = " "

[cmd_duration]
min_time = 30000
format = "[$duration]($style)"
disabled = false

[golang]
symbol = "󰟓 " 
style = "bold blue"
#symbol = ""

[guix_shell]
symbol = " "

[haskell]
symbol = " "

[haxe]
symbol = " "

[hg_branch]
symbol = " "

[hostname]
ssh_symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[kotlin]
symbol = " "

[lua]
symbol = " "

[memory_usage]
symbol = "󰍛 "

[meson]
symbol = "󰔷 "

[nim]
symbol = "󰆥 "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "
disabled = true

[ocaml]
symbol = " "

[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "

[package]
symbol = "󰏗 "

[perl]
symbol = " "

[php]
symbol = " "

[pijul_channel]
symbol = " "

[python]
symbol = " "

[rlang]
symbol = "󰟔 "

[ruby]
symbol = " "

[rust]
symbol = "󱘗 "
style = "bold red"

[scala]
symbol = " "

[swift]
symbol = " "

[sudo]
symbol = "= "
style = 'bold green'

[zig]
symbol = " "
